nav:
  - Getting Started:
      - Introduction: index.md
      - Requirements: requirements.md
      - Deployment:
          - Docker: Deployment.md
          - DigitalOcean: DigitalOcean.md
      - User system: Users.md
      - Advanced topics:
          - Server Configuration: Configuration.md
          - Docker with Let's Encrypt: LetsEncrypt.md
          - Using PostgreSQL: Postgres.md
          - Hosting media on S3: s3.md
          - Limit CPU usage: cpu-limited.md
  - User guide:
      - Introduction: user-guide/index.md
      - Registration: user-guide/registration.md
      - First login: user-guide/first-login.md
      - Add media files: user-guide/media.md
      - Tag people in photos: user-guide/tagging.md
      - Synchronize with Gramps: user-guide/sync.md
  - Backend development:
      - Introduction: dev-backend/index.md
      - Development setup: dev-backend/setup.md
      - API specification: dev-backend/api.md
      - Manual queries: dev-backend/queries.md
  - Frontend development:
      - Introduction: dev-frontend/index.md
      - Architecture: dev-frontend/architecture.md
      - Development setup: dev-frontend/setup.md
      - Translation: dev-frontend/translation.md
site_name: Gramps Web
site_url: https://gramps-project.github.io/web
edit_uri: https://github.com/gramps-project/web/blob/main/docs/
repo_url: https://github.com/gramps-project/Gramps.js
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: brown
    accent: blue
  logo: logo.svg
  favicon: favicon.ico
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
